/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import rs.ac.bg.fon.ps.domain.Paket;
import rs.ac.bg.fon.ps.view.controller.ViewController;
import rs.ac.bg.fon.ps.view.form.component.table.PaketTableModel;

/**
 *
 * @author Lenovo
 */
public class FrmPregledPaketa extends javax.swing.JDialog {

    /**
     * Creates new form FrmPregledPaketa
     */
    public FrmPregledPaketa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
//        try {
//            pripremiPrikaz();
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja forme: \n", "Greska forme paketa", JOptionPane.ERROR_MESSAGE);
//        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaketi = new javax.swing.JTable();
        btnOpsirnije = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbUredjajiPretraga = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnPretraga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled paketa");

        tblPaketi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPaketi);

        btnOpsirnije.setText("Opsirnije");
        btnOpsirnije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpsirnijeActionPerformed(evt);
            }
        });

        btnIzbrisi.setText("Obrisi");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Pretraga paketa"));

        jLabel1.setText("Vrsta uredjaja:");

        btnPretraga.setText("Pretraga");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPretraga)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUredjajiPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUredjajiPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPretraga)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpsirnije)
                            .addComponent(btnIzbrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpsirnije)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzbrisi)
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
//        try {
//            int red = tblPaketi.getSelectedRow();
//            if (red >= 0) {
//            PaketTableModel model = (PaketTableModel) tblPaketi.getModel();
//            Paket paket=model.getPaket(red);
//            int option = JOptionPane.showConfirmDialog(rootPane, "Da li zaista zelite da obrisete paket "+paket.getNazivPaketa() , "Brisanje paketa", JOptionPane.YES_NO_CANCEL_OPTION);
//                if (option == JOptionPane.YES_OPTION) {
//                    Controller.getInstance().obrisiPaket(paket);
//                    JOptionPane.showMessageDialog(this, "Paket uspesno obrisan!\n", "Brisanje paketa", JOptionPane.INFORMATION_MESSAGE);
//                    osveziPrikaz();
//                }
//            }
//        } catch (Exception ex) {
//            ex.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja paketa!\n" + ex.getMessage(), "Brisanje paketa", JOptionPane.ERROR_MESSAGE);
//        }
//
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void btnOpsirnijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpsirnijeActionPerformed
//        int red = tblPaketi.getSelectedRow();
//        if (red >= 0) {
//            PaketTableModel model = (PaketTableModel) tblPaketi.getModel();
//            Paket paket = model.getPaket(red);
//            ViewController.getInstance().pokreniFrmPaket(paket.getPaketID());
//        } else {
//            JOptionPane.showMessageDialog(this, "Morate odabrati paket!", "Opsirnije", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
    }//GEN-LAST:event_btnOpsirnijeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnOpsirnije;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JComboBox<Object> cmbUredjajiPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPaketi;
    // End of variables declaration//GEN-END:variables

//    private void pripremiPrikaz() throws Exception {
//        popuniTabelu();
//    }
//
//    private void dodajNoviPaket() {
//        PaketTableModel model = (PaketTableModel) tblPaketi.getModel();
//        model.dodajPaket(new Paket());
//    }
//
//    private void popuniTabelu() throws Exception {
//        List<Paket> listaPaketa = Controller.getInstance().getAllPaketi();
//        PaketTableModel model = new PaketTableModel(listaPaketa);
//        tblPaketi.setModel(model);
//
//        JComboBox cbUredjaji = new JComboBox(Controller.getInstance().getAllUredjaji().toArray());
//        TableColumn tcUredjaj = tblPaketi.getColumnModel().getColumn(5);
//        tcUredjaj.setCellEditor(new DefaultCellEditor(cbUredjaji));
//    }
//
//    public void osveziPrikaz() throws Exception {
//        List<Paket> listaPaketa = Controller.getInstance().getAllPaketi();
//        PaketTableModel model = (PaketTableModel) tblPaketi.getModel();
//        model.osveziPakete(listaPaketa);
//    }

    public void addBtnOpsirnijeActionListener(ActionListener actionListener) {
        btnOpsirnije.addActionListener(actionListener);
    }



    public void addBtnObrisiActionListener(ActionListener actionListener) {
        btnIzbrisi.addActionListener(actionListener);
    }



    public JButton getBtnIzbrisi() {
        return btnIzbrisi;
    }

    public JButton getBtnOpsirnije() {
        return btnOpsirnije;
    }

    public JTable getTblPaketi() {
        return tblPaketi;
    }

    public javax.swing.JButton getBtnPretraga() {
        return btnPretraga;
    }

    public javax.swing.JComboBox<Object> getCmbUredjajiPretraga() {
        return cmbUredjajiPretraga;
    }

    public void addBtnPretraziActionListener(ActionListener actionListener) {
        btnPretraga.addActionListener(actionListener);
    }
    
    
}
