/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import rs.ac.bg.fon.ps.domain.Paket;
import rs.ac.bg.fon.ps.domain.Uredjaj;
import rs.ac.bg.fon.ps.view.controller.ViewController;
import rs.ac.bg.fon.ps.view.form.component.table.UredjajTableModel;
import rs.ac.bg.fon.ps.view.form.util.FormMode;

/**
 *
 * @author Lenovo
 */
public class FrmPaket extends javax.swing.JDialog {

    /**
     * Creates new form FrmPrijava
     */
    public FrmPaket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        try {
//            pripremaPrikaza(formMode);
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja forme: \n", "Greska forme paketa", JOptionPane.ERROR_MESSAGE);
//        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPaket = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtPaketID = new javax.swing.JTextField();
        txtNazivPaketa = new javax.swing.JTextField();
        lblNazivProizvoda = new javax.swing.JLabel();
        txtBrojSati = new javax.swing.JTextField();
        lblNazivProizvoda1 = new javax.swing.JLabel();
        lblNazivProizvoda2 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        lblNazivProizvoda4 = new javax.swing.JLabel();
        cmbUredjaj = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnOmoguciIzmene = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelPaket.setBorder(javax.swing.BorderFactory.createTitledBorder("Paket"));

        lblID.setText("ID paketa:");

        lblNazivProizvoda.setText("Naziv paketa:");

        lblNazivProizvoda1.setText("Broj sati:");

        lblNazivProizvoda2.setText("Cena:");

        lblNazivProizvoda4.setText("Uredjaj:");

        btnSacuvaj.setText("Sacuvaj paket");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnOmoguciIzmene.setText("Omoguci izmene");

        javax.swing.GroupLayout PanelPaketLayout = new javax.swing.GroupLayout(PanelPaket);
        PanelPaket.setLayout(PanelPaketLayout);
        PanelPaketLayout.setHorizontalGroup(
            PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPaketLayout.createSequentialGroup()
                .addGroup(PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPaketLayout.createSequentialGroup()
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPaketID))
                    .addGroup(PanelPaketLayout.createSequentialGroup()
                        .addComponent(lblNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNazivPaketa))
                    .addGroup(PanelPaketLayout.createSequentialGroup()
                        .addComponent(lblNazivProizvoda1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBrojSati))
                    .addGroup(PanelPaketLayout.createSequentialGroup()
                        .addComponent(lblNazivProizvoda2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCena))
                    .addGroup(PanelPaketLayout.createSequentialGroup()
                        .addComponent(lblNazivProizvoda4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUredjaj, 0, 440, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPaketLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOmoguciIzmene)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)))
                .addContainerGap())
            .addGroup(PanelPaketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPaketLayout.setVerticalGroup(
            PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPaketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtPaketID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivProizvoda)
                    .addComponent(txtNazivPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivProizvoda1)
                    .addComponent(txtBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivProizvoda2)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNazivProizvoda4)
                    .addComponent(cmbUredjaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOmoguciIzmene)
                    .addComponent(btnObrisi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
//        try {
//            
//            Paket paket = paketSaForme();
//            Controller.getInstance().addPaket(paket);
//            JOptionPane.showMessageDialog(this, "Paket uspesno sacuvan!", "Dodavanje paketa", JOptionPane.INFORMATION_MESSAGE);
//            resetForm();
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Greska prilikom dodavanja paketa:\n" + e.getMessage(), "Novi paket", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
//        try {
//            Paket paket = paketSaForme();
//            Controller.getInstance().izmeniPaket(paket);
//            JOptionPane.showMessageDialog(this, "Paket uspesno izmenjen!", "Izmena paketa", JOptionPane.INFORMATION_MESSAGE);
//            ViewController.getInstance().osveziPrikazPaketa();
//            this.dispose();
//        } catch (Exception ex) {
//            Logger.getLogger(FrmPaket.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, "Greska prilikom izmene paketa:\n" + ex.getMessage(), "Izmena paketa", JOptionPane.ERROR_MESSAGE);
//
//        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
//        try {
//            Paket paket = paketSaForme();
//            Controller.getInstance().obrisiPaket(paket);
//            JOptionPane.showMessageDialog(this, "Paket uspesno obrisan!", "Brisanje paketa", JOptionPane.INFORMATION_MESSAGE);
//            ViewController.getInstance().osveziPrikazPaketa();
//            this.dispose();
//        } catch (Exception ex) {
//            Logger.getLogger(FrmPaket.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja paketa:\n" + ex.getMessage(), "Brisanje paketa", JOptionPane.ERROR_MESSAGE);
//
//        }
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPaket;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOmoguciIzmene;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cmbUredjaj;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNazivProizvoda;
    private javax.swing.JLabel lblNazivProizvoda1;
    private javax.swing.JLabel lblNazivProizvoda2;
    private javax.swing.JLabel lblNazivProizvoda4;
    private javax.swing.JTextField txtBrojSati;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNazivPaketa;
    private javax.swing.JTextField txtPaketID;
    // End of variables declaration//GEN-END:variables

    
//    
//    private void popuniCmb() throws Exception {
//        cmbUredjaj.removeAllItems();
//        List<Uredjaj> uredjaji = Controller.getInstance().getAllUredjaji();
//        for (Uredjaj uredjaj : uredjaji) {
//            cmbUredjaj.addItem(uredjaj);
//        }
//    }
//
//    private void resetForm() {
//        txtPaketID.setText("");
//        txtNazivPaketa.setText("");
//        txtCena.setText("");
//        txtBrojSati.setText("");
//    }
//
//    private void pripremaPrikaza(FormMode formMode) throws Exception {
//        popuniCmb();
//        postaviElementeForme(formMode);
//    }
//
//    private void postaviElementeForme(FormMode formMode) {
//        switch (formMode) {
//            case FORMA_DODAVANJE:
//                btnSacuvaj.setVisible(true);
//                btnObrisi.setVisible(false);
//                btnIzmeni.setVisible(false);
//                resetForm();
//                break;
//            case FORMA_IZMENA:
//                txtPaketID.setEnabled(false);
//                btnSacuvaj.setVisible(false);
//                btnObrisi.setVisible(true);
//                btnIzmeni.setVisible(true);
//                popuniFrmPaket();
//                break;
//        }
//    }
//
//    private void popuniFrmPaket() {
//
//        try {
//            int paketID = (int) ViewController.getInstance().getParamMap().get("FORMA_PAKET_OPSIRNIJE");
//            Paket paket = Controller.getInstance().vratiPaket(paketID);
//
//            txtPaketID.setText(String.valueOf(paket.getPaketID()));
//            txtNazivPaketa.setText(paket.getNazivPaketa());
//            txtBrojSati.setText(String.valueOf(paket.getBrojSati()));
//            txtCena.setText(String.valueOf(paket.getCena()));
//            cmbUredjaj.setSelectedItem(paket.getUredjaj());
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
//
//    private Paket paketSaForme() throws Exception {
//        if (txtBrojSati.getText().isEmpty() || txtCena.getText().isEmpty() || txtNazivPaketa.getText().isEmpty() || txtPaketID.getText().isEmpty()) {
//                throw new Exception("Sva polja su obavezna!");
//            }
//        Paket paket = new Paket();
//        paket.setUredjaj((Uredjaj) cmbUredjaj.getSelectedItem());
//        paket.setPaketID(Integer.parseInt(txtPaketID.getText().trim()));
//        paket.setNazivPaketa(txtNazivPaketa.getText().trim());
//        paket.setBrojSati(Integer.parseInt(txtBrojSati.getText().trim()));
//        paket.setCena(Double.parseDouble(txtCena.getText().trim()));
//        paket.setSlobodan(true);
//        return paket;
//    }

    public javax.swing.JPanel getPanelPaket() {
        return PanelPaket;
    }

    public javax.swing.JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public javax.swing.JButton getBtnObrisi() {
        return btnObrisi;
    }

    public javax.swing.JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public JButton getBtnOmoguciIzmene() {
        return btnOmoguciIzmene;
    }

    public javax.swing.JComboBox<Object> getCmbUredjaj() {
        return cmbUredjaj;
    }

    public javax.swing.JTextField getTxtBrojSati() {
        return txtBrojSati;
    }

    public javax.swing.JTextField getTxtCena() {
        return txtCena;
    }

    public javax.swing.JTextField getTxtNazivPaketa() {
        return txtNazivPaketa;
    }

    public javax.swing.JTextField getTxtPaketID() {
        return txtPaketID;
    }

    public void addBtnSacuvajActionListener(ActionListener actionListener) {
        btnSacuvaj.addActionListener(actionListener);
    }

    public void addBtnIzmeniActionListener(ActionListener actionListener) {
        btnIzmeni.addActionListener(actionListener);
    }

    public void addBtnIzbrisiActionListener(ActionListener actionListener) {
        btnObrisi.addActionListener(actionListener);
    }

    public void addBtnOmoguciIzmene(ActionListener actionListener) {
        btnOmoguciIzmene.addActionListener(actionListener);
    }

    public JLabel getLblID() {
        return lblID;
    }
    
    
    
}
